### ISSUE TITLE
Add build job to github actions when pushing / merging to dev branch

### ISSUE THREAD

**Issue by uriahf** [uriahf/rtichoke_python#9]
The same build job should be used when pushing / merging to dev branch, the same way it's been done on main:

https://github.com/uriahf/rtichoke_python/blob/main/.github/workflows/python-package.yml

avoid the pypi-publish part, obviously it should run only on main branch.

Please customize the flow in order to have your own choice of testing package (unittest instead of pytest) and lint package (pylint instead of flake8). 

Good luck :D

**Comment by urigott** [comment]
Done!

The Dev branch now deploys _pull requests_ and _pushes_ into TestPyPi.
The Main workflow will be later adjusted to deploy into PyPi (when we decide that a staged version is reached).

As this was the main issue, I will now close the pull request, and move on to automatic documentation.
